[env]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_DFU_ON_BOOT=0
  -I ../Lib

board_build.partitions = default.csv

upload_protocol = esptool
upload_resetmethod = usb_serial_jtag

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
  iq-motion-control/IQ Module Communication@^1.5.0

[env:bridge]
build_src_filter =
  -<*>
  +<bridge.cpp>

[env:position_sweep]
build_src_filter =
  -<*>
  +<position_sweep.cpp>
